### ISSUE TITLE
Error when sortinghat show

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/sortinghat#117]
When running sortinghat (latest version in pip, 0.5.1) as follows:

```
sortinghat -u jgb -p XXX -d grimoire_sh show
```

I get an error:

```
Traceback (most recent call last):
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'uidentities.last_modified' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/gl/bin/sortinghat", line 181, in <module>
    code = main()
  File "/tmp/gl/bin/sortinghat", line 93, in main
    code = cmd.run(*args.cmd_args)
  File "/tmp/gl/lib/python3.5/site-packages/sortinghat/cmd/show.py", line 78, in run
    code = self.show(params.uuid, params.term)
  File "/tmp/gl/lib/python3.5/site-packages/sortinghat/cmd/show.py", line 105, in show
    uidentities = api.unique_identities(self.db)
  File "/tmp/gl/lib/python3.5/site-packages/sortinghat/api.py", line 974, in unique_identities
    order_by(UniqueIdentity.uuid).all()
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2726, in all
    return list(self)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
    return self._execute_and_instances(context)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/tmp/gl/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/tmp/gl/lib/python3.5/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'uidentities.last_modified' in 'field list'") [SQL: 'SELECT uidentities.uuid AS uidentities_uuid, uidentities.last_modified AS uidentities_last_modified, countries_1.code AS countries_1_code, countries_1.name AS countries_1_name, countries_1.alpha3 AS countries_1_alpha3, profiles_1.uuid AS profiles_1_uuid, profiles_1.name AS profiles_1_name, profiles_1.email AS profiles_1_email, profiles_1.is_bot AS profiles_1_is_bot, profiles_1.country_code AS profiles_1_country_code, identities_1.id AS identities_1_id, identities_1.name AS identities_1_name, identities_1.email AS identities_1_email, identities_1.username AS identities_1_username, identities_1.source AS identities_1_source, identities_1.uuid AS identities_1_uuid, identities_1.last_modified AS identities_1_last_modified \nFROM uidentities LEFT OUTER JOIN profiles AS profiles_1 ON uidentities.uuid = profiles_1.uuid LEFT OUTER JOIN countries AS countries_1 ON countries_1.code = profiles_1.country_code LEFT OUTER JOIN identities AS identities_1 ON uidentities.uuid = identities_1.uuid ORDER BY uidentities.uuid'] (Background on this error at: http://sqlalche.me/e/2j85)
```

**Comment by acs** [comment]
My guess is that you are using a SH => 0.5.0 with a database created with an older version. This old database has and old schema that does not include the uidentities.last_modified.

To fix it just read: https://github.com/grimoirelab/sortinghat#compatibility-between-versions

Closing this bug. If this action does not fix your problem, please, reopen the issue!

**Comment by jgbarah** [comment]
I see. Yes, that could be the problem. Thanks! Now it seems I don't get it, when I re-started the database from scratch.
